def ApproximatePatternCount(Text,Pattern,d):
    count = 0 
    for i in range (len(Text) - len(Pattern) + 1) :
        if HammingDistance(Text[i:i+len(Pattern)],Pattern) <= d :
            count += 1
    return count 
def HammingDistance(p,q) :
    Distance = 0
    for i in range(len(p)) :
        if p[i] != q[i] :
            Distance += 1
    return Distance
print(ApproximatePatternCount("GCAGAAGGCGCCGGATTCGTGGCGCAGTGGCTGTAAGGTCCTAAAACTGACCAGCGTTGTGTCGTCCATTGGTGTAATATAGGGAAACGCTACCTTCGGGCCTCCCCAGCTCTTGCGCTCATCGGGCCCAGTCGAAAGGCAGTCATGCTAGTGCCCCAGTGCTGGGGTTATAGTGATTTAGAATTACACAATTGTCCCGGTGCGAAACTTATATTAATCACCGGTCGGTGATCCCACATCCGAGTCCAAGGCAACGGCATACCAATGTGTCTCCAGTTAACTCTTCCTAAAGCCGCACGGGCCTGTGAGTTCGTAACATTAAACCAAGCGTACTGAATCTCGACACGGCAAAGTCATGGAGGGATCT","TGATTT",3))
